#!/bin/bash
# Quick Integration Checklist for Rate Limiting
# Copy this checklist and mark off as you integrate rate limiting

echo "════════════════════════════════════════════════════════════════"
echo "   دوائي App - Rate Limiting Integration Checklist"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "✅ PHASE 1: Setup (DO THIS FIRST)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  □ Verify lib/rate-limit.ts exists"
echo "  □ Verify lib/RATE_LIMIT_EXAMPLES.ts exists"
echo "  □ Verify lib/RATE_LIMIT_API_EXAMPLES.ts exists"
echo "  □ Read RATE_LIMITING_GUIDE.md completely"
echo ""
echo "  To verify: npm run build (should have no errors)"
echo ""

echo "✅ PHASE 2: Authentication Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  PRIORITY: High (Brute-force protection)"
echo "  LIMIT: 5 attempts per minute"
echo ""
echo "  Endpoint 1: Login"
echo "    □ File: Find your login server action or API route"
echo "    □ Add: import { getClientIP, rateLimitAction, RATE_LIMIT_CONFIG } from '@/lib/rate-limit'"
echo "    □ Add: const clientIP = getClientIP()"
echo "    □ Add: await rateLimitAction(clientIP, RATE_LIMIT_CONFIG.auth)"
echo "    □ Wrap in try/catch with error.code === 'RATE_LIMIT_EXCEEDED'"
echo "    □ Test: Try logging in 6+ times quickly - should get Arabic error"
echo ""
echo "  Endpoint 2: Registration/Signup"
echo "    □ File: Find your signup server action or API route"
echo "    □ Apply same changes as Login"
echo "    □ Test: Try signing up 6+ times quickly - should get Arabic error"
echo ""
echo "  Endpoint 3: Password Reset (if applicable)"
echo "    □ File: Find password reset endpoint"
echo "    □ Apply same changes with RATE_LIMIT_CONFIG.auth"
echo ""

echo "✅ PHASE 3: Search Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  PRIORITY: Medium (Prevent search abuse)"
echo "  LIMIT: 30 requests per minute"
echo ""
echo "  Endpoint 1: Medicine Search"
echo "    □ File: app/actions/medicines.ts or app/api/medicines/search/route.ts"
echo "    □ Add rate limit check with RATE_LIMIT_CONFIG.search"
echo "    □ Test: Perform 31+ searches quickly - should get rate limit error"
echo ""
echo "  Endpoint 2: Pharmacy Search/Nearby"
echo "    □ File: app/actions/pharmacies-nearby.ts or similar"
echo "    □ Add rate limit check with RATE_LIMIT_CONFIG.search"
echo "    □ Test: Load nearby pharmacies 31+ times - should get rate limit error"
echo ""

echo "✅ PHASE 4: Prescription Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  PRIORITY: High (Security-sensitive operations)"
echo "  LIMIT: 10 requests per minute"
echo ""
echo "  Endpoint 1: Upload Prescription"
echo "    □ File: app/actions/prescriptions.ts or app/api/prescriptions/upload/route.ts"
echo "    □ Add rate limit check with RATE_LIMIT_CONFIG.prescription"
echo "    □ Test: Upload 11+ prescriptions quickly - should get rate limit error"
echo ""
echo "  Endpoint 2: Submit Prescription to Pharmacies"
echo "    □ File: app/actions/prescriptions-advanced.ts or similar"
echo "    □ Add rate limit check with RATE_LIMIT_CONFIG.prescription"
echo ""

echo "✅ PHASE 5: Testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  □ Test with same IP address"
echo "    - Make 5+ login attempts quickly → Should get rate limit"
echo "    - Make 30+ searches quickly → Should get rate limit"
echo "    - Make 10+ prescription uploads → Should get rate limit"
echo ""
echo "  □ Test with different IPs (if possible)"
echo "    - Use VPN or different network"
echo "    - Each IP should have independent limit"
echo ""
echo "  □ Verify error messages"
echo "    - Should see Arabic text when rate limited"
echo "    - Example: 'عذراً، لقد تجاوزت عدد محاولات التسجيل...'"
echo ""
echo "  □ Check normal usage"
echo "    - Make 1 login attempt → Should succeed"
echo "    - Make 1 search → Should succeed"
echo "    - Make 1 prescription upload → Should succeed"
echo ""
echo "  □ Verify Retry-After header (for API routes)"
echo "    - Open browser DevTools → Network tab"
echo "    - Make requests until rate limited"
echo "    - Should see 'Retry-After' header in response"
echo ""

echo "✅ PHASE 6: Documentation & Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  □ Update API documentation"
echo "    - List which endpoints have rate limiting"
echo "    - Document the limits (5, 10, 30 per minute)"
echo "    - Explain Arabic error messages"
echo ""
echo "  □ Consider monitoring"
echo "    - Add logging to rate-limit.ts in production"
echo "    - Track which IPs/users are hitting limits"
echo "    - Monitor for DDoS attempts"
echo ""
echo "  □ Test in production (low traffic period)"
echo "    - Deploy code to staging environment"
echo "    - Verify rate limiting works with real traffic"
echo "    - Check for false positives (legitimate users getting blocked)"
echo ""
echo "  □ Deploy to production"
echo "    - npm run build"
echo "    - npm run start"
echo "    - Monitor logs for errors"
echo ""

echo "✅ PHASE 7: Future Enhancements"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Consider later (not required now):"
echo "  □ Switch to Redis for distributed rate limiting"
echo "  □ Implement per-user limits (not just per-IP)"
echo "  □ Add whitelist for internal/trusted IPs"
echo "  □ Add DDoS detection and auto-blocking"
echo "  □ Create admin dashboard to view rate limit metrics"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   Quick Command Reference"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  Build the project:"
echo "    npm run build"
echo ""
echo "  Find files to modify:"
echo "    grep -r 'loginAction\\|uploadPrescription' app/"
echo ""
echo "  Review rate limit utility:"
echo "    cat lib/rate-limit.ts"
echo ""
echo "  See integration examples:"
echo "    cat lib/RATE_LIMIT_EXAMPLES.ts"
echo "    cat lib/RATE_LIMIT_API_EXAMPLES.ts"
echo ""
echo "  Read full guide:"
echo "    cat RATE_LIMITING_GUIDE.md"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "   Questions?"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  1. How do I find where to add the code?"
echo "     → Search for 'loginAction', 'uploadPrescription' in app/"
echo ""
echo "  2. What if my action is named differently?"
echo "     → Same approach - add the rate limit check first"
echo ""
echo "  3. How do I test rate limiting?"
echo "     → Make requests in a loop: for i in {1..11}; do curl ...; done"
echo ""
echo "  4. Why Arabic error messages?"
echo "     → This is a medical app in Arabic - users expect Arabic"
echo ""
echo "  5. Can I adjust limits?"
echo "     → Yes! Edit RATE_LIMIT_CONFIG in lib/rate-limit.ts"
echo ""
echo "════════════════════════════════════════════════════════════════"
